[versions]
agp = "8.5.2"
kotlin = "1.9.0"
core = "1.13.0"
appcompat = "1.7.0"
fragment = "1.8.5"
desugar = "2.1.3"

[libraries]
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

